### PR TITLE
A more declarative sidebar

### PR DESCRIPTION
**Pull request by cmc333333**
This removes some chunks of logic from the JS where it can be implemented in the templates. It also attempts to make the sidebar less special-case, allowing arbitrary sidebars to be added and removed without needing new JS views to be created.

See the individual changesets for more. In service of 18f/atf-eregs#376

@xtine I think you have the most experience here now. Would you mind reviewing?

### CODE REVIEW

**Comment by xtine** [comment]
What was `help-view.js` doing before?

**Comment by cmc333333** [comment]
As I understand it, `help-view.js` had no specific functionality (it just targeted a chunk of the DOM). This `childView` could then be easily deleted/added.

This PR takes a different approach, removing the explicit need to call out each component of the sidebar in JS via `viewlessChildren`, which also removes the elements from the DOM when needed.

**Comment by xtine** [comment]
This looks good, I like taking out more of the markup that was in the placeholder functions. Do you mind putting in a comment description about `viewlessChildren` does though?

**Comment by cmc333333** [comment]
:+1: can do

**Comment by cmc333333** [comment]
Hold off on merging -- I introduced a bug w/ that last commit

**Comment by cmc333333** [comment]
Alright, fixed and ready for review! See last commit for an explanation of the problem

**Pull request merged**
