### PR TITLE
Use MultipartEncoder to assemble payload

### PR DESCRIPTION
**Pull request by vrajmohan**

### CODE REVIEW

**Comment by jmcarp** [comment]
If I'm reading it right, this patch changes the expected request we get from the client, such that we expect a single comment field instead of an array of per-section comment snippets. Is it preferable to assemble the comment on the client rather than on the server? I can change the frontend if so--just wondering.

**Comment by jmcarp** [comment]
Related to my comment from a minute ago: the frontend allows users to attach files to specific per-section or per-paragraph comments, but the backend ignores attachment-section associations and simply uploads all the files. That behavior didn't change in this patch, but I'm wondering if we should include some metadata indicating which file belongs to which section--or change the frontend so that users don't expect those associations to be sent to regs.gov.

cc @cmc333333 @donjo @jehlers

**Comment by vrajmohan** [comment]
You are right in that this commit expects an _already-assembled_ single comment field. I was punting on the assembly itself since this is work-in-progress. I do feel that the assembly itself is still more easily done in the back-end.

**Comment by cmc333333** [comment]
I'd generally agree that assembly on the backend is the way to go, but it sounds like there's a big push to show the user the assembled comment _before_ they submit.

Re files, I think we want to reference them in the assembled comment. Something like:
```
<< Section X.A.4 >>
See attached file, "data.csv."
```

**Comment by jmcarp** [comment]
We can also expose a preview view on the backend to allow users to preview their comments, then use the same logic on submission. The only issue I can see with client-side assembly is that users could maliciously (kind of?) submit invalid comments--for example, referring to sections or files that don't exist. Which, of course, we can validate server-side, but that seems like more work. So I think I'd have a slight preference for server-side preview and assembly--but what do you all think?

Either way, I think this patch looks good, and we can refine comment assembly in a separate PR. Will merge.

**Comment by cmc333333** [comment]
Quick note that we don't need to worry about users submitting malicious comments. They can already do that :) I think the only server-side validation we need to perform is around attachments.

I'm generally in favor of server-side rendering, but in this case, I don't think it'll make a huge difference.

**Pull request merged**
