### PR TITLE
41 pending comments

### PR DESCRIPTION
**Pull request by jmcarp**
Add navigation for pending comments to write view per mocks. Totally unstyled! It looks like this:

t6peppro2a

Would love feedback and help with styling from @xtine and @jehlers!

### CODE REVIEW

**Comment by cmc333333** [comment]
Seems like a step in the right direction. Two not-terribly-important thoughts:
* the term table-of-contents threw me for a bit; that has a pretty specific meaning elsewhere in the app
* this is a lot of JS code (comment-toc-view.js) to do something my naive brain thinks is relatively simple. Is there a way to pare this down or re-use existing functions?

**Comment by jehlers** [comment]
@jmcarp This is a great start. Only style thoughts at this point would be this:

- Move list of added comments to the right sidebar 
- "Edit" should be a blue or standard color link
- "Clear" should probably be red

**Comment by jmcarp** [comment]
@cmc333333: I'm thinking about moving comment storage to a model and associated collection, which should cut down the views in general. Meanwhile, does anything particular jump as at you as duplicative or boilerplate-y?

**Comment by cmc333333** [comment]
We spoke a bit about this out of band, but documenting here for transparency:

I think the biggest issue is around `parseComments`, which seems like a utility more than something specific to this listing. I'm betting that'd be resolved by your model/collection suggestion.

I also wondered if Backbone has less boilerplate-y support for templates in its views, but that doesn't appear to be the case.

I got nothin :)

**Comment by jmcarp** [comment]
Made some changes:

* Re-positioned comment index
* Moved comment-related views to more sensible places
* Renamed to `CommentIndexView`

@xtine: could you take a look at the js changes?

**Comment by xtine** [comment]
* If I click "View the Proposal" button on a comment write page that already has a comment, it goes to a blank screen.
* Should adding a new comment populate the right sidebar? I have to refresh to see any new comments that were added
* Clearing a comment also should remove the item on the right sidebar

Also wondering if CommentListView would be a better name since it's a listing of user comments. Not sure if index would clash with anything else named so far.

**Comment by xtine** [comment]
👍

**Pull request merged**
