### PR TITLE
Removing redundant parts of readme; updating URL; phrasing

### PR DESCRIPTION
**Pull request by brittag**
* The two intro-to-eRegs sections of this readme (the screenshot and features list) are better handled by the link to the centralized eRegs documentation (https://eregs.github.io/features/) rather than getting repeated in this readme for regulations-site, so I removed those two intro sections.

* I also updated the documentation site link and clarified the two-worlds explanation.

### CODE REVIEW

**Comment by brittag** [comment]
Added another commit with more streamlining:

* This readme has two very-similar sections both titled "JavaScript Application", so I removed one of them.

* It also has two very-similar sections about how to build the Sphinx docs, so I removed one of them.

**Comment by brittag** [comment]
While I'm poking around looking for redundant things, it probably makes sense to remove this long-ago changelog file.

**Comment by brittag** [comment]
Another change I noticed while poking around: http://regulations-site.readthedocs.org/en/latest/index.html didn't seem to be linked from this readme, so I added a link.

**Comment by cmc333333** [comment]
:+1: excellent

**Pull request merged**
