### PR TITLE
bug fix: replace top margin for third level collapsed paragraph markers

### PR DESCRIPTION
**Pull request by xtine**

### CODE REVIEW

**Comment by cmc333333** [comment]
Hm. Why is `level-3` special? What about `level-4`, -5, -6, etc?

**Comment by xtine** [comment]
is there a max depth of levels for the markers? i'm wondering if there's a better way to find these cases than just finding the level depth.

**Comment by cmc333333** [comment]
Hypothetically, there is no max depth. Practically, I wouldn't expect anything below level 8.

I'd bet there's a better way. Let's take a step back; the original problem centered around collapsed markers not displaying correctly. Why did they display correctly before? How do the paragraph markers in the US Code chunks (478.103), which use a very related scheme, display correctly?

Why does the `.collapsed + ol` fix part of the problem? Why must it be reset on some (but not all) inner ols?

**Comment by xtine** [comment]
So inspecting the stylesheets a bit more, this bug is apparent between the on collapsed level-3 and deeper markers because there are `.level-1` and `.level-2` specific margin-top settings in the typography.less files.

**Comment by cmc333333** [comment]
Aha! I can imagine level-1 having special significance, but I don't know why level-2 or below would need to appear different (perhaps resetting the level-1 styles?). Is there a way to rewrite these paragraph marker styles to account for the special case of level-1, alone?

Also, ping ping @ascott1 in case he has insights here

**Comment by xtine** [comment]
In the `typography.less` file starting after line 347 (List Styles section):

`.level-1 > li p {
    margin-top: 0;
}`

`.level-2 > li > p {
    margin-top: 1em;
}`

So my takeaway is that the level-2 styling is to "reset" the top margin of level-1 ... so level-3 and below would not have the margin set.

**Comment by cmc333333** [comment]
So would something like 

```
.level-2 > li.collapsed > p { margin-top: 0; }
```

both 1) work and 2) require less setting/resetting/re-resetting?

Am I conveying the underlying thought well? Rather than having logic for level-1, level-3, level-4, etc., let's invert it and only have logic for our special case: level-2.

**Comment by xtine** [comment]
That was my exactly my thought, but I'm trying make sure if there was a reason why it was done that way and if it doesn't cascade into any list style formatting issues.

**Comment by cmc333333** [comment]
@xtine, just had a quick chat with @ascott1 to see if he remembered what was going on.

We didn't dig into it super deeply, but his best guess is that the _first_ `level-1` paragraphs is supposed to have a top margin to separate it from the section titles. Additional `level-1` paragraphs most likely cancel this out with bottom margins or something similar. He'd prefer a better strategy (maybe it's as simple as adding a bottom margin to the section header?) if you can think of one.

**Comment by xtine** [comment]
@cm: so upon closer inspection, it seems it is the margins for ordered lists that is making collapsed paragraphs have uneven spacing. so i removed margins on ordered lists entirely, but putting in a top margin for level-1 and removing the top margin for level-2. this seems to work, but let me know if you see any issues with it.

**Comment by cmc333333** [comment]
@xtine I can't visualize what you're describing well, so I'll trust you. That said, should we be removing/moving https://github.com/18F/regulations-site/blob/3d1dfb905de0e4bd3da4e434165311a1dbd8fc47/regulations/static/regulations/css/less/typography.less#L343-L373 ? The last rule there seems to conflict.

**Comment by xtine** [comment]
I think `typography.less` is being overwritten on the atf-eregs side so I forgot to remove it.

**Pull request merged**
